"""Structured subprocess suites executed by the release selftest."""

import os
import subprocess


REFACTOR_SAFETY_SUITES = (
    ("共享状态内核回归",
     ("scripts/tests/test_state_core.py",), 90, 3000),
    ("内嵌能力完整生命周期回归",
     ("scripts/tests/test_capabilities.py",), 240, 5000),
    ("内置规格引擎回归与差分对拍",
     ("scripts/tests/test_specengine.py",), 300, 5000),
    ("开发检查点与最终增量检视回归",
     ("scripts/tests/test_checkpoints.py",), 180, 5000),
    ("跨单提交归属与 STORY 本地化回归",
     ("scripts/tests/test_commit_ownership.py",), 180, 5000),
    ("CodeCheck 全链路诊断日志回归",
     ("scripts/tests/test_codecheck_logging.py",), 180, 5000),
    ("质量任务范围、函数边界与执行目录回归",
     ("scripts/tests/test_task_scope.py",), 180, 5000),
    ("轻量编码预检跨语言与安全降级回归",
     ("scripts/tests/test_lightcheck.py",), 180, 5000),
    ("Workflow 定义与转移策略回归",
     ("scripts/tests/test_workflow_definition.py",), 180, 5000),
    ("Workflow 推进策略与适配器回归",
     ("scripts/tests/test_workflow_advancement.py",), 180, 5000),
    ("Workflow 完成裁决与适配器回归",
     ("scripts/tests/test_workflow_completion.py",), 180, 5000),
    ("Gate 请求解析策略回归",
     ("scripts/tests/test_guard_intent.py",), 180, 5000),
    ("Gate 编辑裁决策略回归",
     ("scripts/tests/test_guard_gate.py",), 180, 5000),
    ("Gate 一次性放行令策略回归",
     ("scripts/tests/test_guard_permits.py",), 180, 5000),
    ("Gate 提交归属策略回归",
     ("scripts/tests/test_guard_ownership.py",), 180, 5000),
    ("Gate 通用 Bash 与 Git 策略回归",
     ("scripts/tests/test_guard_bash.py",), 180, 5000),
    ("Gate 一次性放行令入口回归",
     ("scripts/tests/test_guard_permit_integration.py",), 180, 5000),
    ("质量任务卡纯契约回归",
     ("scripts/tests/test_quality_task_cards.py",), 180, 5000),
    ("CodeCheck 纯策略回归",
     ("scripts/tests/test_quality_codecheck.py",), 180, 5000),
    ("交付子状态机纯策略回归",
     ("scripts/tests/test_delivery_policies.py",), 180, 5000),
    ("CLI 命令路由契约回归",
     ("scripts/tests/test_command_dispatch.py",), 180, 5000),
    ("行为差分安全网",
     ("scripts/tests/test_differential_harness.py",), 180, 5000),
    ("完整 Phase-10 行为差分",
     ("scripts/tests/differential/runner.py",
      "--implementation-root", "."), 300, 5000),
    ("重构架构边界",
     ("scripts/tests/test_architecture.py",), 180, 5000),
    ("受管文件句柄",
     ("scripts/tests/test_file_io.py",), 180, 5000),
    ("重构完成契约与覆盖清单",
     ("scripts/tests/test_refactor_completion.py",), 180, 5000),
    ("故障注入与原子写失败回归",
     ("scripts/tests/test_fault_injection.py",), 180, 5000),
    ("Evidence 值对象与注册执行回归",
     ("scripts/tests/test_evidence.py",), 180, 5000),
    ("Workflow Evidence 通用规则回归",
     ("scripts/tests/test_evidence_rules.py",), 180, 5000),
    ("Agent Evidence 令牌与检视回归",
     ("scripts/tests/test_agent_evidence.py",), 180, 5000),
    ("Delivery Evidence 提交与推送回归",
     ("scripts/tests/test_delivery_evidence.py",), 180, 5000),
    ("Delivery 不可变用例结果回归",
     ("scripts/tests/test_delivery_models.py",), 180, 5000),
    ("Delivery Checkpoint 计划用例回归",
     ("scripts/tests/test_delivery_checkpoint_use_cases.py",), 180, 5000),
    ("Delivery Checkpoint 用户裁决用例回归",
     ("scripts/tests/test_delivery_checkpoint_decisions.py",), 180, 5000),
    ("Delivery Checkpoint 最终收据用例回归",
     ("scripts/tests/test_delivery_checkpoint_final.py",), 180, 5000),
    ("Delivery Checkpoint 状态路由用例回归",
     ("scripts/tests/test_delivery_checkpoint_status.py",), 180, 5000),
    ("Delivery Checkpoint 恢复编排用例回归",
     ("scripts/tests/test_delivery_checkpoint_recovery.py",), 180, 5000),
    ("Delivery Standalone 生命周期用例回归",
     ("scripts/tests/test_delivery_standalone_use_cases.py",), 180, 5000),
    ("Delivery Moonlight 生命周期用例回归",
     ("scripts/tests/test_delivery_moonlight_use_cases.py",), 180, 5000),
    ("Quality Evidence CodeCheck 回归",
     ("scripts/tests/test_quality_evidence.py",), 180, 5000),
)


def execute_refactor_safety_suites(
        root, python_executable, report, run=None):
    """Execute every registered suite and report every result immediately."""
    run = run or subprocess.run
    for label, command, timeout, output_limit in REFACTOR_SAFETY_SUITES:
        result = run(
            [
                python_executable,
                os.path.join(root, command[0]),
                *command[1:],
            ],
            text=True,
            encoding="utf-8",
            errors="replace",
            capture_output=True,
            check=False,
            timeout=timeout,
        )
        report(
            label,
            result.returncode == 0,
            (result.stdout + result.stderr)[-output_limit:],
        )
